import { Bricolage_Grotesque, Young_Serif } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/AppSidebar";
import { UserProvider } from "@/context/user";
import AuthStateChangeProvider from "@/context/auth";

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

const youngSerif = Young_Serif({
  variable: "--font-young-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${youngSerif.variable} ${bricolageGrotesque.variable} antialiased flex font-bricolage-grotesque bg-[#E4E0F3]`}
      >
        <UserProvider>
          <AuthStateChangeProvider>
            <AppSidebar />
            {children}
          </AuthStateChangeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
